### ISSUE TITLE
imgur help

### ISSUE THREAD

**Issue by DSaliou** [MarkRedeman/Imgur-Laravel#1]
How I can move or post a picture from my computer to imgur with ( Laravel Input::get('name') ). Please give me an exemple

**Comment by MarkRedeman** [comment]
Posting a picture using this package will use the same code as when the [Adyg/php-imgur-api-client](https://github.com/Adyg/php-imgur-api-client/blob/master/doc/Image.md) would be used.
You can find an example of posting a picture [here](https://github.com/Adyg/php-imgur-api-client/blob/master/doc/Image.md).

The `$client` variable can be retrieved using the service container:
```
// uploading an image
$client = App::make('Imgur\Client');

$imageData = array(
        'image' => $pathToFile,
        'type'  => 'file',
        'name' => 'Lipsum',
        'title' => 'Lorem Ipsum',
        'description' => 'Lorem Ipsum Dolor Sit Amet'
    );

$basic = $client->api('image')->upload($imageData);
```

**Comment by DSaliou** [comment]
Thank it right
